# Setup
title:               'Ravirer'
tagline:             'A digital garden on queer utopias and activism'
description:         'One's attempt at sense-making'
url:                 ''
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Ariane Beaudin
  url:               https://www.instagram.com/ariane.beaudin/
  email:             ariane.beaudin@hotmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
